/// Treatment guidance — hardcoded from treatment_guidance.yaml
/// One block per disease. Source-cited. Updateable without retraining models.
class GuidanceBlock {
  final String disease;
  final String defaultTriage;
  final String whatItIs;
  final List<String> doNow;
  final List<String> doNot;
  final List<String> medicines;
  final String referTo;
  final List<String> tellFacility;
  final List<String> watchFor;
  final List<String> homeCare;
  final String followUp;
  final String source;

  const GuidanceBlock({
    required this.disease,
    required this.defaultTriage,
    required this.whatItIs,
    this.doNow = const [],
    this.doNot = const [],
    this.medicines = const [],
    this.referTo = '',
    this.tellFacility = const [],
    this.watchFor = const [],
    this.homeCare = const [],
    this.followUp = '',
    required this.source,
  });
}

class TreatmentGuidance {
  static GuidanceBlock? lookup(String disease) => _blocks[disease];

  static GuidanceBlock fallback() => const GuidanceBlock(
        disease: 'unknown',
        defaultTriage: 'urgent',
        whatItIs: 'Diagnosis uncertain. Refer to physician for evaluation.',
        doNow: ['Reassure patient', 'Refer to nearest PHC for evaluation'],
        referTo: 'Nearest PHC',
        source: 'CureBay default protocol',
      );

  static const Map<String, GuidanceBlock> _blocks = {
    'snakebite': GuidanceBlock(
      disease: 'snakebite',
      defaultTriage: 'emergency',
      whatItIs: 'Snake has bitten the patient. Venom may cause bleeding, paralysis, or kidney damage.',
      doNow: [
        'Keep patient calm and lying down — movement spreads venom faster',
        'Immobilize the bitten limb with a splint',
        'Remove rings, watches, tight clothing BEFORE swelling increases',
        'Mark the edge of swelling with pen and note the time',
        'Note snake appearance if seen',
      ],
      doNot: [
        'Do NOT apply tourniquet — causes limb loss',
        'Do NOT cut the wound or try to suck out venom',
        'Do NOT apply ice, herbs, cow dung, or traditional remedies',
        'Do NOT give aspirin or blood-thinning medicines',
      ],
      referTo: 'Nearest CHC or District Hospital with Anti-Snake Venom (ASV). Travel time <1 hour.',
      tellFacility: ['Time of bite', 'Body part bitten', 'Snake description', 'Symptoms: bleeding, drooping eyelids, breathing'],
      watchFor: ['Drooping eyelids', 'Bleeding gums or nose', 'Cola-coloured urine', 'Difficulty breathing'],
      source: 'National Snakebite Management Protocol, MoHFW 2017',
    ),
    'acute_mi': GuidanceBlock(
      disease: 'acute_mi',
      defaultTriage: 'emergency',
      whatItIs: 'Heart attack — blood supply to heart muscle is blocked. Every minute matters.',
      doNow: [
        'Sit/lie patient down comfortably, head slightly raised',
        'Loosen tight clothing around chest and neck',
        'Note EXACT time chest pain started',
        'If aspirin available AND no bleeding history: 300mg aspirin to chew',
      ],
      doNot: [
        'Do NOT let patient walk or exert themselves',
        'Do NOT give food or water',
        'Do NOT delay referral',
      ],
      medicines: ['Aspirin 300mg (chewed) if available and no contraindication'],
      referTo: 'Nearest hospital with cardiac care or CCU. Use fastest available transport.',
      tellFacility: ['Time chest pain started', 'Aspirin given (Y/N + time)', 'Diabetes/BP status'],
      watchFor: ['Loss of consciousness', 'Vomiting', 'Worsening breathlessness'],
      source: 'ICMR Cardiovascular Disease Guidelines',
    ),
    'stroke': GuidanceBlock(
      disease: 'stroke',
      defaultTriage: 'emergency',
      whatItIs: 'Brain attack — blood flow to brain blocked or bleeding. Treatment window only 4-5 hours.',
      doNow: [
        'Note EXACT time symptoms began (or last time normal)',
        'Lay patient on side to prevent choking',
        'Do FAST check: Face / Arm / Speech / Time',
        'Keep patient warm and reassure',
      ],
      doNot: [
        'Do NOT give food, water, or oral medicine — patient may choke',
        'Do NOT give aspirin — could worsen brain bleed',
        'Do NOT wait to see if symptoms improve',
      ],
      referTo: 'Stroke-capable hospital (CT scan + neurology) within 4 hours of onset.',
      tellFacility: ['EXACT time symptoms started', 'FAST findings', 'BP/pulse', 'Anticoagulant medication history'],
      watchFor: ['Worsening consciousness', 'Vomiting', 'Seizures'],
      source: 'Indian Stroke Association Guidelines',
    ),
    'cholera': GuidanceBlock(
      disease: 'cholera',
      defaultTriage: 'emergency',
      whatItIs: 'Severe watery diarrhea from contaminated water. Patient can lose dangerous fluid in hours.',
      doNow: [
        'Start ORS immediately if patient is awake — small sips every 5 min',
        'Adult: 200-400 ml after each loose stool',
        'Child <5: 50-100 ml after each stool',
        'If unable to drink → REFER for IV fluids',
        'Alert IDSP / district health office',
      ],
      doNot: [
        'Do NOT give plain water alone',
        'Do NOT give anti-diarrheal medicines like loperamide',
      ],
      medicines: ['ORS as much as patient can drink', 'Zinc for children'],
      referTo: 'Nearest PHC/CHC with IV fluids if patient cannot drink, drowsy, or has sunken eyes.',
      tellFacility: ['Number of loose stools', 'Vomiting', 'Last urine', 'Other cases in village'],
      watchFor: ['Sunken eyes', 'Skin pinch slow', 'Weak pulse', 'Confusion'],
      source: 'WHO Cholera Treatment Guidelines + ICMR-NICED + IDSP/MoHFW',
    ),
    'malaria': GuidanceBlock(
      disease: 'malaria',
      defaultTriage: 'urgent',
      whatItIs: 'Mosquito-borne infection causing fever with chills. Treatable if caught early.',
      doNow: [
        'Get blood test (RDT or microscopy) at PHC',
        'Give paracetamol for fever',
        'Encourage 2-3 L fluids/day',
        'Use bed net at night',
      ],
      doNot: [
        'Do NOT start anti-malarial without confirmation',
        'Do NOT ignore worsening symptoms (drowsiness/jaundice/dark urine = severe)',
      ],
      medicines: ['Paracetamol 500mg-1g every 6 hours', 'ORS if dehydrated'],
      referTo: 'PHC or CHC for blood test and antimalarial treatment. Same day.',
      tellFacility: ['Fever pattern', 'Travel history', 'Other cases in family/village'],
      watchFor: ['Yellow eyes/skin', 'Dark tea-coloured urine', 'Drowsiness', 'Convulsions'],
      source: 'NVBDCP National Framework for Malaria Elimination',
    ),
    'dengue': GuidanceBlock(
      disease: 'dengue',
      defaultTriage: 'urgent',
      whatItIs: 'Mosquito-borne viral fever with body pain. Can become severe with bleeding/shock.',
      doNow: [
        'Encourage oral fluids: water, ORS, coconut water — 2-3 L/day',
        'Give paracetamol for fever',
        'Get NS1 antigen or platelet count test',
        'Use mosquito net even during day',
      ],
      doNot: [
        'Do NOT give aspirin or ibuprofen — increases bleeding',
        'Do NOT ignore warning signs after fever subsides',
      ],
      medicines: ['Paracetamol only — never NSAIDs', 'ORS / coconut water'],
      referTo: 'PHC for testing and platelet monitoring. Same day.',
      tellFacility: ['Day of fever', 'Bleeding from gums/nose', 'Persistent vomiting', 'Abdominal pain'],
      watchFor: ['Bleeding gums/nose/skin spots', 'Severe abdominal pain', 'Cold clammy skin', 'Restlessness'],
      source: 'NVBDCP Dengue National Guidelines',
    ),
    'typhoid': GuidanceBlock(
      disease: 'typhoid',
      defaultTriage: 'urgent',
      whatItIs: 'Bacterial infection from contaminated food/water. Causes prolonged fever and weakness.',
      doNow: [
        'Get blood test (Widal or blood culture) at PHC',
        'Encourage rest and soft food',
        'Encourage fluids',
        'Hand hygiene',
      ],
      doNot: ['Do NOT start antibiotics without testing', 'Do NOT give heavy/spicy food'],
      medicines: ['Paracetamol for fever', 'ORS if dehydrated'],
      referTo: 'PHC or CHC for testing and antibiotic. Within 24 hours.',
      watchFor: ['Severe abdominal pain (perforation)', 'Blood in stool', 'Confusion'],
      source: 'ICMR Enteric Fever Treatment Guidelines',
    ),
    'tuberculosis': GuidanceBlock(
      disease: 'tuberculosis',
      defaultTriage: 'urgent',
      whatItIs: 'Bacterial lung infection. Spreads through coughing. Curable with 6-month treatment under NTEP (FREE).',
      doNow: [
        'Refer for sputum test (CBNAAT/microscopy) at TB-DOTS center — FREE',
        'Cover cough with cloth',
        'Identify family members for screening',
      ],
      doNot: ['Do NOT start TB medicines without confirmation', 'Do NOT stop treatment if started'],
      referTo: 'Nearest TB-DOTS center / PHC under NTEP (Ni-kshay portal).',
      watchFor: ['Coughing up blood', 'Severe breathlessness'],
      source: 'NTEP (RNTCP) Technical Guidelines India',
    ),
    'pneumonia': GuidanceBlock(
      disease: 'pneumonia',
      defaultTriage: 'urgent',
      whatItIs: 'Lung infection causing cough, fever, and difficulty breathing. Needs antibiotics.',
      doNow: ['Count breathing rate', 'Check oxygen if oximeter available', 'Encourage fluids', 'Give paracetamol'],
      doNot: ['Do NOT delay antibiotics for adults with clear pneumonia signs'],
      medicines: ['Paracetamol', 'Amoxicillin per physician prescription'],
      referTo: 'PHC or CHC for examination and antibiotics. Same day.',
      watchFor: ['Bluish lips', 'Cannot speak full sentences', 'Confusion'],
      source: 'ICMR Standard Treatment Guidelines for Community Acquired Pneumonia',
    ),
    'severe_pneumonia_child': GuidanceBlock(
      disease: 'severe_pneumonia_child',
      defaultTriage: 'emergency',
      whatItIs: 'Severe lung infection in a child. Fast breathing AND chest sucking inward — danger signs.',
      doNow: [
        'Count breaths for full minute when child is calm',
        'Look for chest indrawing',
        'Give first dose of oral amoxicillin if available (per IMCI)',
        'Keep child warm',
        'Continue breastfeeding in small amounts',
      ],
      doNot: ['Do NOT delay referral', 'Do NOT give cough suppressants', 'Do NOT stop breastfeeding'],
      medicines: ['Amoxicillin oral first dose', 'Paracetamol if fever 10-15 mg/kg'],
      referTo: 'Nearest hospital with pediatric care and oxygen. Same hour.',
      tellFacility: ['Respiratory rate', 'SpO2', 'Chest indrawing', 'First dose given', 'Child weight'],
      watchFor: ['Bluish lips/nails', 'Cannot drink', 'Convulsions', 'Unusual sleepiness'],
      source: 'WHO IMCI Severe Pneumonia + IAP STG',
    ),
    'severe_dehydration_child': GuidanceBlock(
      disease: 'severe_dehydration_child',
      defaultTriage: 'emergency',
      whatItIs: 'Child has lost too much fluid from diarrhea/vomiting. IV fluids needed urgently.',
      doNow: ['Check IMCI Plan C signs', 'Start ORS in small frequent sips', 'Continue breastfeeding', 'Give zinc'],
      doNot: ['Do NOT delay referral', 'Do NOT give anti-diarrheal drugs'],
      medicines: ['ORS', 'Zinc 10-20mg daily x 14 days'],
      referTo: 'Nearest facility with IV fluids. Within 1 hour.',
      tellFacility: ['Number of stools', 'Hours since last urine', 'Child weight', 'Conscious level'],
      watchFor: ['Becoming unresponsive', 'Sunken fontanelle', 'Cold extremities'],
      source: 'WHO IMCI Plan C Dehydration Management',
    ),
    'japanese_encephalitis': GuidanceBlock(
      disease: 'japanese_encephalitis',
      defaultTriage: 'emergency',
      whatItIs: 'Brain infection from mosquito bite. Causes high fever, seizures, confusion. Life-threatening.',
      doNow: ['Lay on side (recovery position)', 'If seizing: clear area, do NOT restrain, time it', 'Cool with wet cloth'],
      doNot: ['Do NOT put anything in mouth during seizure', 'Do NOT give oral medicines if unconscious'],
      medicines: ['Paracetamol if can swallow safely'],
      referTo: 'Nearest hospital with pediatric/neuro care. Fastest transport.',
      watchFor: ['Repeated seizures', 'Worsening consciousness', 'Difficulty breathing'],
      source: 'NVBDCP JE Programme Guidelines',
    ),
    'sickle_cell_crisis': GuidanceBlock(
      disease: 'sickle_cell_crisis',
      defaultTriage: 'emergency',
      whatItIs: 'Severe pain crisis in sickle cell disease — abnormal blood cells block vessels.',
      doNow: ['Hydrate well', 'Keep warm (cold triggers crisis)', 'Paracetamol for pain', 'Check chest pain/breathing'],
      doNot: ['Do NOT ignore chest pain in sickle cell patient', 'Do NOT use ice'],
      medicines: ['Paracetamol 15 mg/kg'],
      referTo: 'Facility with sickle cell management + blood bank. Same day.',
      watchFor: ['Chest pain/breathing (acute chest syndrome)', 'Stroke (FAST)', 'Severe abdominal pain'],
      source: 'ICMR National Sickle Cell Anaemia Mission',
    ),
    'heat_stroke': GuidanceBlock(
      disease: 'heat_stroke',
      defaultTriage: 'emergency',
      whatItIs: 'Body temperature dangerously high (>40°C). Brain and organs may be damaged.',
      doNow: ['Move to cool place — shade, fan, AC', 'Remove outer clothing', 'Spray/sponge with cool water', 'Fan continuously'],
      doNot: ['Do NOT give paracetamol — does not work for heat stroke', 'Do NOT use ice directly'],
      referTo: 'Nearest hospital with IV fluids. Same day, urgent.',
      watchFor: ['Seizures', 'Loss of consciousness', 'No improvement with cooling'],
      source: 'NDMA Heat Wave Guidelines India',
    ),
    'leprosy': GuidanceBlock(
      disease: 'leprosy',
      defaultTriage: 'urgent',
      whatItIs: 'Bacterial skin and nerve infection. Curable with multi-drug therapy. Early detection prevents disability.',
      doNow: ['Examine all skin patches in good light', 'Test sensation with cotton wisp', 'Refer to NLEP-designated facility for FREE MDT'],
      doNot: ['Do NOT stigmatize patient — modern treatment makes them non-infectious in days'],
      referTo: 'Nearest NLEP-designated PHC. Same week.',
      watchFor: ['Weakness in hand or foot', 'Painless ulcers on numb skin'],
      source: 'NLEP Operational Guidelines + WHO Leprosy Strategy',
    ),
    'hypertension_uncontrolled': GuidanceBlock(
      disease: 'hypertension_uncontrolled',
      defaultTriage: 'urgent',
      whatItIs: 'Blood pressure is too high. Increases risk of stroke, heart attack, and kidney damage.',
      doNow: ['Re-check BP after 5 min rest, both arms', 'Educate: less salt, no tobacco, daily walking', 'Ensure regular medicine intake'],
      doNot: ['Do NOT stop BP medicines because patient feels fine'],
      referTo: 'PHC under NPCDCS. Same day if SBP >180 or DBP >110.',
      watchFor: ['Severe headache + vision changes', 'Chest pain', 'Stroke symptoms'],
      source: 'ICMR Hypertension Guidelines + NPCDCS',
    ),
    'type2_diabetes_uncontrolled': GuidanceBlock(
      disease: 'type2_diabetes_uncontrolled',
      defaultTriage: 'urgent',
      whatItIs: 'Blood sugar too high. Long-term damage to eyes, kidneys, nerves, heart.',
      doNow: ['Check random glucose if glucometer available', 'Refer to PHC/CHC for HbA1c', 'Educate diet + walking', 'Check feet for wounds'],
      doNot: ['Do NOT skip prescribed medicines', 'Do NOT ignore foot wounds'],
      referTo: 'PHC under NPCDCS. Within 24h if glucose >300.',
      watchFor: ['Confusion, deep breathing, fruity breath (DKA)', 'Fainting (hypoglycemia)', 'Foot wounds not healing'],
      source: 'ICMR Diabetes Guidelines + NPCDCS',
    ),
    'iron_deficiency_anemia': GuidanceBlock(
      disease: 'iron_deficiency_anemia',
      defaultTriage: 'normal',
      whatItIs: 'Low hemoglobin from iron deficiency. Common in women and children.',
      doNow: ['Refer for Hb test under Anemia Mukt Bharat', 'Iron-rich foods: green leafy veg, jaggery, dates', 'Avoid tea/coffee with meals'],
      doNot: ['Do NOT take iron with milk or tea'],
      medicines: ['IFA tablets per Anemia Mukt Bharat', 'Albendazole 400mg deworming'],
      homeCare: ['Iron-rich diet', 'IFA supplementation', 'Deworm every 6 months'],
      referTo: 'PHC under Anemia Mukt Bharat. Within a week.',
      followUp: 'Re-check Hb after 3 months',
      watchFor: ['Breathlessness on minimal exertion', 'Chest pain', 'Fainting'],
      source: 'Anemia Mukt Bharat Operational Guidelines',
    ),
    'copd_exacerbation': GuidanceBlock(
      disease: 'copd_exacerbation',
      defaultTriage: 'urgent',
      whatItIs: 'Worsening of chronic lung disease, often in smokers or those exposed to indoor smoke.',
      doNow: ['Sit patient upright', 'Use prescribed inhaler', 'Give oxygen if SpO2 <90%', 'Pursed-lip breathing'],
      doNot: ['Do NOT use sedatives', 'Do NOT lay patient flat'],
      referTo: 'CHC or hospital with nebulization and oxygen. Same day.',
      watchFor: ['Bluish lips', 'Confusion', 'Cannot speak in sentences'],
      source: 'ICMR COPD Guidelines + GOLD India',
    ),
    'neonatal_jaundice': GuidanceBlock(
      disease: 'neonatal_jaundice',
      defaultTriage: 'urgent',
      whatItIs: 'Newborn baby has yellow skin or eyes. Mild is normal but high levels can damage brain.',
      doNow: ['Examine in natural daylight', 'Encourage frequent breastfeeding 8-12 times/day', 'Refer for bilirubin test'],
      doNot: ['Do NOT expose to direct sunlight as treatment', 'Do NOT give water/glucose water'],
      referTo: 'Facility with phototherapy unit. Same day if jaundice extends below knees or age <24h.',
      watchFor: ['Lethargy or poor feeding', 'High-pitched cry / arching back', 'Seizures'],
      source: 'WHO IMCI Newborn Care + IAP Guidelines',
    ),
    'chikungunya': GuidanceBlock(
      disease: 'chikungunya',
      defaultTriage: 'urgent',
      whatItIs: 'Mosquito-borne viral fever causing severe joint pain.',
      doNow: ['Paracetamol for pain', '2-3 L fluids/day', 'Rest joints', 'Use mosquito net'],
      doNot: ['Do NOT give aspirin/ibuprofen until dengue ruled out'],
      referTo: 'PHC for confirmation and dengue rule-out. Same day.',
      watchFor: ['Bleeding (rule out dengue)', 'Joint pain >2 weeks'],
      source: 'NVBDCP Chikungunya Guidelines',
    ),
    'scrub_typhus': GuidanceBlock(
      disease: 'scrub_typhus',
      defaultTriage: 'urgent',
      whatItIs: 'Tick-borne fever common in monsoon. Treatable with doxycycline.',
      doNow: ['Look for eschar (black scab) in armpit/groin/behind knee', 'Refer for IgM ELISA test', 'Paracetamol'],
      referTo: 'CHC for testing and doxycycline. Same day.',
      watchFor: ['Confusion (meningoencephalitis)', 'Difficulty breathing', 'Yellow eyes', 'Reduced urine'],
      source: 'ICMR Scrub Typhus Treatment Guidelines',
    ),
    'filariasis': GuidanceBlock(
      disease: 'filariasis',
      defaultTriage: 'urgent',
      whatItIs: 'Parasite spread by mosquitoes affecting lymph system. Causes leg/arm/scrotum swelling.',
      doNow: ['Refer for night blood smear', 'Wash limb daily with soap', 'Elevate limb when resting', 'Treat any cuts'],
      referTo: 'PHC for diagnosis under NVBDCP-ELF. Within a week.',
      watchFor: ['High fever with red painful swollen limb (acute attack)'],
      source: 'NVBDCP Elimination of Lymphatic Filariasis Programme',
    ),
    'viral_fever_uri': GuidanceBlock(
      disease: 'viral_fever_uri',
      defaultTriage: 'normal',
      whatItIs: 'Common viral infection — cold/flu. Resolves on its own in 5-7 days.',
      doNow: ['Rest at home', 'Drink plenty warm fluids', 'Steam inhalation 2-3x/day', 'Saltwater gargling'],
      doNot: ['Do NOT demand antibiotics — viruses don\'t respond', 'Do NOT share utensils'],
      medicines: ['Paracetamol if fever 500mg-1g every 6h adult'],
      homeCare: ['Stay hydrated', 'Rest 5-7 days', 'Isolate from elderly/infants'],
      referTo: 'PHC if fever persists >3 days or new symptoms develop.',
      followUp: 'Return if fever >3 days or breathlessness',
      watchFor: ['Difficulty breathing', 'Severe headache or stiff neck', 'Persistent vomiting'],
      source: 'Standard Primary Care Guidelines',
    ),
    'acute_diarrhea': GuidanceBlock(
      disease: 'acute_diarrhea',
      defaultTriage: 'normal',
      whatItIs: 'Loose stools usually from contaminated food/water. Most cases resolve in 2-3 days with fluids.',
      doNow: ['Start ORS immediately — small sips frequently', 'Continue normal diet (incl. breastfeeding)', 'Hand hygiene'],
      doNot: ['Do NOT give anti-diarrheals to children', 'Do NOT stop feeding', 'Do NOT give sugary drinks'],
      medicines: ['ORS 200-400ml after each loose stool (adult)', 'Zinc 20mg/day x 14 days for children >6mo'],
      homeCare: ['ORS continuously', 'Easy foods: rice water, banana, curd', 'Boil drinking water'],
      referTo: 'PHC if no improvement in 2 days.',
      followUp: 'Return if blood in stool, severe dehydration, no improvement in 2 days',
      watchFor: ['Blood in stool', 'No urine 6h, no tears', 'Lethargy in children', 'Persistent vomiting'],
      source: 'WHO IMCI Diarrhea Management',
    ),
    'gastritis': GuidanceBlock(
      disease: 'gastritis',
      defaultTriage: 'normal',
      whatItIs: 'Inflammation of stomach lining. Often from spicy food, stress, or NSAIDs.',
      doNow: ['Eat small frequent meals', 'Avoid spicy/oily food', 'Avoid NSAIDs', 'Quit smoking/alcohol'],
      doNot: ['Do NOT take ibuprofen/painkillers', 'Do NOT skip meals'],
      medicines: ['Antacid syrup or tablet', 'Paracetamol if pain (NOT ibuprofen)'],
      homeCare: ['Bland diet for a week', 'Avoid trigger foods'],
      referTo: 'PHC if pain severe or no improvement in 1 week.',
      watchFor: ['Vomiting blood / coffee-ground material', 'Black tarry stools', 'Severe pain', 'Weight loss'],
      source: 'Standard Primary Care Guidelines',
    ),
    'uti': GuidanceBlock(
      disease: 'uti',
      defaultTriage: 'normal',
      whatItIs: 'Urinary tract infection — burning urination, frequent urination, sometimes mild fever.',
      doNow: ['Drink 3+ L water/day', 'Urinate frequently, don\'t hold', 'Wipe front to back (women)', 'Refer for urine test'],
      doNot: ['Do NOT use harsh soaps', 'Do NOT stop antibiotics early'],
      medicines: ['Antibiotic per physician prescription', 'Paracetamol if pain'],
      homeCare: ['Hydration', 'Frequent urination', 'Complete antibiotic course'],
      referTo: 'PHC for urine test and antibiotic. Same day.',
      followUp: 'Return if fever, flank pain, vomiting, blood in urine',
      watchFor: ['High fever with chills', 'Flank/back pain (kidney infection)', 'Vomiting', 'Pregnant women — refer urgently'],
      source: 'ICMR UTI Management Guidelines',
    ),
    'migraine': GuidanceBlock(
      disease: 'migraine',
      defaultTriage: 'normal',
      whatItIs: 'Severe one-sided headache with nausea, often with sensitivity to light/sound.',
      doNow: ['Move to dark, quiet room', 'Cold compress on forehead', 'Sleep if possible', 'Hydrate, eat light'],
      doNot: ['Do NOT overuse painkillers', 'Do NOT ignore new patterns with weakness/vision changes'],
      medicines: ['Paracetamol 1g for adult', 'Ibuprofen if not contraindicated'],
      homeCare: ['Rest in dark room', 'Identify and avoid triggers', 'Maintain sleep schedule'],
      referTo: 'PHC if frequent attacks or any neurological symptoms.',
      followUp: 'Return if headaches more frequent, severe, or change pattern',
      watchFor: ['Sudden severe thunderclap headache', 'With fever and stiff neck', 'With weakness/vision loss/confusion (stroke)'],
      source: 'Indian Headache Society Guidelines',
    ),
  };
}
